sadhguru.url=https://isha.sadhguru.org
consciousplanet.url=https://consciousplanet.org
lingabhairavi.url=https://lingabhairavi.org
shivanga.url=https://www.shivanga.org
mahashivarathri.url=https://mahashivarathri.org
auth.enabled=false