sadhguru.url=https://uat.sadhguru.org
consciousplanet.url=https://uat.consciousplanet.org
lingabhairavi.url=https://uat.lingabhairavi.org
shivanga.url=https://uat.shivanga.org
mahashivarathri.url=https://uat.mahashivarathri.org
auth.enabled=true
auth.user=admin
auth.pass=isha123
payment.expected=fail